# Generated by Django 3.2 on 2021-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
            },
        ),
    ]
