# Generated by Django 3.2 on 2021-05-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='status',
        ),
        migrations.AddField(
            model_name='lot',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='veh_type',
            field=models.CharField(choices=[('B', 'Bicycle'), ('BS', 'Bus'), ('C', 'Car'), ('CT', 'Consumer Truck'), ('M', 'Motorcycle'), ('T', 'Truck'), ('ST', 'Semi Truck'), ('V', 'Van')], default='C', max_length=50),
        ),
    ]
