# Generated by Django 3.2 on 2021-05-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('_type', models.CharField(choices=[('B', 'Bicycle'), ('BS', 'Bus'), ('C', 'Car'), ('CT', 'Consumer Truck'), ('M', 'Motorcycle'), ('T', 'Truck'), ('ST', 'Semi Truck'), ('V', 'Van')], max_length=4)),
                ('owner', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
